### ISSUE TITLE
Incompatibility with IE (edge)

### ISSUE THREAD

**Issue by joedaouddotcom** [cats-with-potatos/chat-app#23]
### Messaging functionality not working correctly.

Logged in user cannot see messages they are sending and the messages from other users (in different browsers do not appear). IE user can see that other users are typing but never sees the sent message.

Errors in console:

```
TypeError: Unable to get property 'push' of undefined or null reference
   at Anonymous function (http://localhost:8080/js/app.js:29941:9)
   at Scope.prototype.$eval (http://localhost:8080/js/app.js:16374:9)
   at $applyAsyncExpression (http://localhost:8080/js/app.js:16514:11)
   at flushApplyAsync (http://localhost:8080/js/app.js:16767:11)
   at Scope.prototype.$eval (http://localhost:8080/js/app.js:16374:9)
   at Scope.prototype.$apply (http://localhost:8080/js/app.js:16474:13)
   at Anonymous function (http://localhost:8080/js/app.js:16778:11)
   at completeOutstandingRequest (http://localhost:8080/js/app.js:5764:7)
   at Anonymous function (http://localhost:8080/js/app.js:6041:7)
SyntaxError: Invalid character
   at Anonymous function (http://localhost:8080/js/app.js:29940:9)
   at Scope.prototype.$eval (http://localhost:8080/js/app.js:16374:9)
   at $applyAsyncExpression (http://localhost:8080/js/app.js:16514:11)
   at flushApplyAsync (http://localhost:8080/js/app.js:16767:11)
   at Scope.prototype.$eval (http://localhost:8080/js/app.js:16374:9)
   at Scope.prototype.$apply (http://localhost:8080/js/app.js:16474:13)
   at Anonymous function (http://localhost:8080/js/app.js:16778:11)
   at completeOutstandingRequest (http://localhost:8080/js/app.js:5764:7)
   at Anonymous function (http://localhost:8080/js/app.js:6041:7)
```

(_This may be something that is resolved with PR #21  gets merged_ )

**Comment by RafGDev** [comment]
Can someone please check this again? I can't because I don't have a windows computer.
